### PR TITLE
#167 - Ensured that both mp4 and m4v video formats are handled

### LINKED ISSUE #167: Only mp4 videos are handled, m4v videos are ignored.
## Expected Behaviour

Both mp4 and m4v videos should be handled, as per how Android handles videos within Storm bundles.

## Current Behaviour

mp4 videos are handled correctly, but m4v videos are not.

## Possible Solution

Add an array defining the supported video file extensions, then check when attempting to open the video link that the extension is in the supported list.

## Steps to Reproduce (for bugs)

1. Within a Storm app, attempt to tap on a video that is of the m4v video type.
2. It does not load.
3. Attempt to tap on a video that is of the mp4 video type.
4. It does load.

## Context

This issue has occurred after the YouTube removal (a033c7f0bc731ab154faf6099a45e243f2045e57), where in VideoListItem.swift

```swift
	videoRow.parentNavigationController?.push(videos: videos)
```

was changed to instead be

```swift
        guard let video = videos.first(where: { $0.localeString == StormLanguageController.shared.currentLanguage }) ?? videos.first, let link = video.link else {
            return
        }
		
        parentNavigationController?.push(link: link)
```

This meant that the file extension checks were then being enforced, and m4v videos would no longer be presented.

## Your Environment

* ThunderCloud version: v1.3.1
* iOS / macOS version: n/a
* Link to your project, if public: n/a

### PR DESCRIPTION
**Pull request by ryanbourneuk**
## Description

Fixes #167, where m4v videos would not be correctly handled.

## Related Issue

Fixes #167

## Motivation and Context

This change is required in order to match the android equivalent of this library - which handles mp4 and mv4 videos.

## How Has This Been Tested?

I have tested this, by making the change within the affected app's carthage submodule, and running the app with this change.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: ThunderCloud/NavigationController.swift [hunk 1]
```diff
@@ -73,6 +73,10 @@ public extension UINavigationController {
     /// Returns a shared instance of `UINavigationController`
     static let shared: UINavigationController = UINavigationController()
     
+    /// Defines the video formats that are supported within Storm apps.
+    /// While the MIME type of video/mp4 is checked when uploading, m4v videos can also have this MIME type.
+    private static let supportedVideoFormats: [String] = ["mp4", "m4v"]
```
Comment (simonmitchell) [inline ThunderCloud/NavigationController.swift]: Unsure whether this makes more sense on `UINavigationController` or `Video`?

Comment (ryanbourneuk) [reply ThunderCloud/NavigationController.swift]: Yeah this is true. Let me move it to Video! :D

Comment (ryanbourneuk) [reply ThunderCloud/NavigationController.swift]: @simonmitchell updated in 26cea8bbe93fe6c74dd8954e5d9aceaecbf92f47 :D
