### PR TITLE
#190 - remove unneeded configure calls to remove duplicated buttons

### LINKED ISSUE #190: Duplicated Buttons within ButtonListItem
## Expected Behaviour

When showing a ButtonListItem, there should only be one button per link.

## Current Behaviour

Links are being duplicated & multiple buttons are appearing.

## Possible Solution

Remove duplicated configure calls, as these are automatically called upon `super.init(...)`

## Steps to Reproduce (for bugs)

1. Have a ButtonListItem within a page, with a single button.
2. Navigate to that page in the app.
3. See that the button is duplicated.

## Your Environment

* ThunderCloud version: v1.4.0

### PR DESCRIPTION
**Pull request by ryanbourneuk**
## Description

Resolves #190, removing the duplicated buttons

## Related Issue

#190 

## Motivation and Context

Buttons should not be duplicated for each link.

## How Has This Been Tested?

It has been run in the context of the affected app, and unit tests have been updated to ensure that the right amount of links are generated.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: ThunderCloud/ButtonListItem.swift [hunk 1]
```diff
@@ -54,8 +54,6 @@ open class ButtonListItem: ListItem {
     /// - Parameter dictionary: A Storm object dictionary.
 	public required init(dictionary: [AnyHashable : Any]) {
 		super.init(dictionary: dictionary)
-		
-		configure(with: dictionary, languageController: StormLanguageController.shared)
```
Comment (simonmitchell) [inline ThunderCloud/ButtonListItem.swift]: Ahhhh, because it subclasses from `ListItem` now which does all this configure shizzle too!
