### PR TITLE
Fixes streaming pages content not rendering

### LINKED ISSUE #170: Streaming pages don't render images
## Expected Behaviour

When streaming a content page, the downloaded images should be displayed to the user correctly.

## Current Behaviour

When streaming a content page, if any images on it aren't either bundled with the app, or downloaded in a delta bundle then the image will not be loaded by Storm when rendering the content. 

## Possible Solution

Make sure `ContentController` also looks in the streamed page directory for content.

## Steps to Reproduce (for bugs)

1. Setup a new page in Storm and publish to live with an image that has been newly uploaded.
2. Add line in your App's `AppDelegate` to force-stream the page:
```
defer {
    self.handleContentNotificationFor(cacheURL: "cache://pages/PAGE_ID_HERE.json")
}
```
3. Witness that the image on the page is blank.

## Context

Streaming pushes not working for ARC First Aid on an old version of the app which wasn't bundled with the content.

## Your Environment

* ThunderCloud version: N/A (Before versioning began)
* iOS / macOS version: iOS 11.3.1
* Link to your project, if public: N/A

### PR DESCRIPTION
**Pull request by simonmitchell**
## Description

Makes sure that the streamed bundle is checked when pulling content using ContentController, as otherwise the app relies on having that content in a bundle or delta update.

We have exposed the directory that `StreamingPagesController` saves data to, and added checks to all content methods in `ContentController` to check said directory for content as well as the delta and original bundle directory!

## Related Issue

Fixes #170 

## How Has This Been Tested?

Has been tested in ARC First Aid manually by calling the code in the attached issue.

### Before
Simulator Screen Shot - iPhone 6 - 2019-08-06 at 14 52 40

### After
Simulator Screen Shot - iPhone 6 - 2019-08-06 at 15 19 50

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: ThunderCloud/ContentController.swift [hunk 1]
```diff
@@ -1224,6 +1246,13 @@ public extension ContentController {
             }
         }
         
+        if let streamDirectory = StreamingPagesController.streamingCacheURL {
+            let fileStreamedPath = streamDirectory.appendingPathComponent(file).path
+            if (FileManager.default.fileExists(atPath: fileStreamedPath)) {
```
Comment (ryanbourneuk) [inline ThunderCloud/ContentController.swift]: Are the brackets needed? :)
